import { LodatKind, LodatSaleStatus, type LodatListItem } from '@crmanhung/shared';

function plot(
  partial: LodatListItem,
): LodatListItem {
  return partial;
}

/** Domain lodats §8 — Mở bán / Tạm dừng, Nhà / Đất, thiếu trường. */
export const mockLodats: LodatListItem[] = [
  plot({
    id: 'ld_lk5_37',
    title: 'LK5 - 37 Mặt sông',
    address: 'Khu Đô Thị Đồng Khê - Hồng Phong',
    areaM2: 90,
    frontageM: 4.5,
    direction: 'Bắc',
    priceVnd: 2_600_000_000,
    priceNote: 'Thương lượng',
    commissionPercent: 1,
    status: LodatSaleStatus.DANG_BAN,
    kind: LodatKind.DAT,
    coverImageUrl: '/mock/lodats/p1.svg',
    extraPhotoCount: 3,
    customerHint: 'Trần Thị Bích',
    updatedAt: '2026-08-16T15:08:42.000',
  }),
  plot({
    id: 'ld_lk3_12',
    title: 'LK3 - 12 Đường 20m',
    address: 'Khu Đô Thị An Hưng - An Đồng',
    areaM2: 100,
    frontageM: 5,
    direction: 'Đông Nam',
    priceVnd: 3_150_000_000,
    priceNote: 'Giá chốt',
    commissionPercent: 1.2,
    status: LodatSaleStatus.DANG_BAN,
    kind: LodatKind.DAT,
    coverImageUrl: '/mock/lodats/p2.svg',
    extraPhotoCount: 5,
    customerHint: 'Nguyễn Văn An',
    updatedAt: '2026-08-16T11:22:10.000',
  }),
  plot({
    id: 'ld_bt08',
    title: 'BT-08 Biệt thự vườn',
    address: 'Khu Đô Thị Đồng Khê - Hồng Phong',
    areaM2: 220,
    frontageM: 10,
    direction: 'Nam',
    priceVnd: 8_900_000_000,
    priceNote: 'Bao sổ',
    commissionPercent: 0.8,
    status: LodatSaleStatus.DANG_BAN,
    kind: LodatKind.NHA,
    coverImageUrl: '/mock/lodats/p3.svg',
    extraPhotoCount: 2,
    customerHint: 'Lê Minh Khoa',
    updatedAt: '2026-08-15T09:40:00.000',
  }),
  plot({
    id: 'ld_a15',
    title: 'Nền A-15 Quán Táo Đông',
    address: 'Quán Táo Đông - An Đồng',
    areaM2: 80,
    frontageM: 4,
    direction: 'Tây',
    priceVnd: 1_850_000_000,
    priceNote: null,
    commissionPercent: 1.5,
    status: LodatSaleStatus.DANG_BAN,
    kind: LodatKind.DAT,
    coverImageUrl: '/mock/lodats/p4.svg',
    extraPhotoCount: 1,
    customerHint: 'Phạm Thu Hà',
    updatedAt: '2026-08-10T16:05:33.000',
  }),
  plot({
    id: 'ld_lk7_21',
    title: 'LK7 - 21 Góc 2 mặt tiền',
    address: 'Khu Đô Thị Nam Hải',
    areaM2: 112,
    frontageM: 6,
    direction: 'Đông Bắc',
    priceVnd: 4_200_000_000,
    priceNote: 'Thương lượng',
    commissionPercent: 1,
    status: LodatSaleStatus.TAM_DUNG,
    kind: LodatKind.DAT,
    coverImageUrl: '/mock/lodats/p5.svg',
    extraPhotoCount: 0,
    customerHint: 'Hoàng Đức',
    updatedAt: '2026-08-08T08:12:00.000',
  }),
  plot({
    id: 'ld_no_photo',
    title: 'LK2 - 05 Gần công viên',
    address: 'Khu Đô Thị An Hưng - An Đồng',
    areaM2: 75,
    frontageM: 4,
    direction: 'Bắc',
    priceVnd: 1_720_000_000,
    priceNote: 'Giá mềm',
    commissionPercent: 1,
    status: LodatSaleStatus.DANG_BAN,
    kind: LodatKind.DAT,
    coverImageUrl: null,
    extraPhotoCount: 0,
    customerHint: null,
    updatedAt: '2026-08-14T13:01:19.000',
  }),
  plot({
    id: 'ld_no_price',
    title: 'SH-03 Shophouse mặt đường',
    address: 'Trục chính KĐT Đồng Khê',
    areaM2: 96,
    frontageM: 6,
    direction: 'Đông',
    priceVnd: null,
    priceNote: 'Chưa chốt giá',
    commissionPercent: null,
    status: LodatSaleStatus.DANG_BAN,
    kind: LodatKind.NHA,
    coverImageUrl: '/mock/lodats/p6.svg',
    extraPhotoCount: 4,
    customerHint: 'Inbox Page',
    updatedAt: '2026-08-16T07:55:00.000',
  }),
  plot({
    id: 'ld_no_specs',
    title: 'Lô góc chờ đo đạc',
    address: 'Hồng Phong - An Dương',
    areaM2: null,
    frontageM: null,
    direction: null,
    priceVnd: 2_100_000_000,
    priceNote: 'Tạm tính',
    commissionPercent: 1,
    status: LodatSaleStatus.DANG_BAN,
    kind: LodatKind.DAT,
    coverImageUrl: '/mock/lodats/p1.svg',
    extraPhotoCount: 0,
    customerHint: 'Trần Thị Bích',
    updatedAt: '2026-08-13T18:20:44.000',
  }),
  plot({
    id: 'ld_no_addr',
    title: 'Nền B-09',
    address: null,
    areaM2: 88,
    frontageM: 4.2,
    direction: 'Tây Nam',
    priceVnd: 1_980_000_000,
    priceNote: null,
    commissionPercent: 1,
    status: LodatSaleStatus.DANG_BAN,
    kind: LodatKind.DAT,
    coverImageUrl: '/mock/lodats/p2.svg',
    extraPhotoCount: 2,
    customerHint: 'Nguyễn Văn An',
    updatedAt: '2026-08-12T10:11:08.000',
  }),
  plot({
    id: 'ld_lk4_18',
    title: 'LK4 - 18 View hồ',
    address: 'Khu Đô Thị Đồng Khê - Hồng Phong',
    areaM2: 95,
    frontageM: 5,
    direction: 'Nam',
    priceVnd: 2_850_000_000,
    priceNote: 'Thương lượng',
    commissionPercent: 1,
    status: LodatSaleStatus.DANG_BAN,
    kind: LodatKind.DAT,
    coverImageUrl: '/mock/lodats/p3.svg',
    extraPhotoCount: 6,
    customerHint: null,
    updatedAt: '2026-08-16T19:44:21.000',
  }),
  plot({
    id: 'ld_lk6_02',
    title: 'LK6 - 02 Gần trường',
    address: 'Khu Đô Thị Nam Hải',
    areaM2: 80,
    frontageM: 4,
    direction: 'Bắc',
    priceVnd: 1_990_000_000,
    priceNote: 'Bao phí',
    commissionPercent: 1.3,
    status: LodatSaleStatus.DANG_BAN,
    kind: LodatKind.DAT,
    coverImageUrl: '/mock/lodats/p4.svg',
    extraPhotoCount: 1,
    customerHint: 'Lê Minh Khoa',
    updatedAt: '2026-08-15T21:03:55.000',
  }),
  plot({
    id: 'ld_c22',
    title: 'Nền C-22 Mặt đường 13m',
    address: 'Quán Táo Đông - An Đồng',
    areaM2: 105,
    frontageM: 5.2,
    direction: 'Đông',
    priceVnd: 2_450_000_000,
    priceNote: null,
    commissionPercent: 1,
    status: LodatSaleStatus.DANG_BAN,
    kind: LodatKind.DAT,
    coverImageUrl: '/mock/lodats/p5.svg',
    extraPhotoCount: 0,
    customerHint: 'Phạm Thu Hà',
    updatedAt: '2026-07-28T14:16:00.000',
  }),
  plot({
    id: 'ld_pause_2',
    title: 'LK1 - 30 Chờ hạ tầng',
    address: 'Khu Đô Thị An Hưng - An Đồng',
    areaM2: 90,
    frontageM: 4.5,
    direction: 'Tây',
    priceVnd: 2_200_000_000,
    priceNote: 'Tạm dừng rao',
    commissionPercent: 1,
    status: LodatSaleStatus.TAM_DUNG,
    kind: LodatKind.DAT,
    coverImageUrl: '/mock/lodats/p6.svg',
    extraPhotoCount: 3,
    customerHint: 'Hoàng Đức',
    updatedAt: '2026-08-01T06:30:00.000',
  }),
  plot({
    id: 'ld_lk9_41',
    title: 'LK9 - 41 Cuối dãy',
    address: 'Khu Đô Thị Đồng Khê - Hồng Phong',
    areaM2: 78,
    frontageM: 4,
    direction: 'Nam',
    priceVnd: 1_680_000_000,
    priceNote: 'Giá tốt',
    commissionPercent: 1.1,
    status: LodatSaleStatus.DANG_BAN,
    kind: LodatKind.DAT,
    coverImageUrl: '/mock/lodats/p1.svg',
    extraPhotoCount: 2,
    customerHint: 'Trần Thị Bích',
    updatedAt: '2026-08-16T08:00:12.000',
  }),
];
