import {
  CustomerStatus,
  UserRole,
  type AuthUser,
  type CustomerDetail,
  type CustomerMessengerMessage,
} from '@crmanhung/shared';

export const MOCK_STAFF: AuthUser = {
  id: 'user_staff_1',
  username: 'staff',
  fullName: 'Bùi Xuân Khả',
  role: UserRole.STAFF,
};

export const MOCK_ADMIN: AuthUser = {
  id: 'user_admin_1',
  username: 'admin',
  fullName: 'Admin Demo',
  role: UserRole.ADMIN,
};

const OTHER_EMPLOYEE_ID = 'user_staff_other';

function staffCustomer(
  partial: Omit<CustomerDetail, 'employeeId' | 'employeeName'> &
    Partial<Pick<CustomerDetail, 'employeeId' | 'employeeName'>>,
): CustomerDetail {
  return {
    employeeId: MOCK_STAFF.id,
    employeeName: MOCK_STAFF.fullName,
    ...partial,
    latestNeedSummary: partial.latestNeedSummary ?? partial.note ?? null,
  };
}

/** Domain §8 + vài dòng để bảng trông giống ảnh mẫu. */
export const mockCustomers: CustomerDetail[] = [
  staffCustomer({
    id: 'cus_net_phones',
    fullName: 'Trần Thị Bích',
    status: CustomerStatus.KHACH_NET,
    budgetMinVnd: 1_500_000_000,
    budgetMaxVnd: 2_000_000_000,
    note: 'Hỏi lô 38 Quán Táo Đông',
    isPinned: true,
    isHidden: false,
    primaryPhone: '0912345678',
    phones: [
      { id: 'ph2', phone: '0912345678', label: 'Chính' },
      { id: 'ph3', phone: '0987654321', label: 'Phụ' },
    ],
    facebook: null,
    latestCareNote: 'Hẹn xem đất cuối tuần',
    lodatCount: 2,
    createdAt: '2026-06-15T08:00:00.000Z',
    updatedAt: '2026-08-16T15:30:00.000Z',
    careNotes: [
      {
        id: 'care2',
        note: 'Hẹn xem đất cuối tuần',
        employeeId: MOCK_STAFF.id,
        employeeName: MOCK_STAFF.fullName,
        createdAt: '2026-08-16T15:30:00.000Z',
      },
    ],
  }),
  staffCustomer({
    id: 'cus_moi_fb',
    fullName: 'Nguyễn Văn An',
    status: CustomerStatus.KHACH_MOI,
    budgetMinVnd: null,
    budgetMaxVnd: null,
    note: 'Inbox hỏi lô mặt tiền',
    isPinned: true,
    isHidden: false,
    primaryPhone: '0901234567',
    phones: [{ id: 'ph1', phone: '0901234567', label: 'Zalo Khả' }],
    facebook: {
      customerUid: 'fb_1001',
      threadId: 'thread_1001',
      facebookName: 'Nguyen Van An FB',
      avatarUrl: null,
      scanSource: 'business_suite',
    },
    latestCareNote: 'Vừa inbox hỏi lô mặt tiền',
    lodatCount: 0,
    createdAt: '2026-07-01T08:00:00.000Z',
    updatedAt: '2026-08-16T10:00:00.000Z',
    careNotes: [
      {
        id: 'care1',
        note: 'Vừa inbox hỏi lô mặt tiền',
        employeeId: MOCK_STAFF.id,
        employeeName: MOCK_STAFF.fullName,
        createdAt: '2026-08-16T10:00:00.000Z',
      },
    ],
  }),
  staffCustomer({
    id: 'cus_pin_3',
    fullName: 'Lê Hoàng Nam',
    status: CustomerStatus.KHACH_NET,
    budgetMinVnd: 800_000_000,
    budgetMaxVnd: 1_200_000_000,
    note: 'Cần đất gần đường tỉnh',
    isPinned: true,
    isHidden: false,
    primaryPhone: '0977656280',
    phones: [{ id: 'ph6', phone: '0977656280', label: 'Zalo Khả' }],
    facebook: null,
    latestCareNote: 'Đã gửi bảng giá khu Đông',
    lodatCount: 1,
    createdAt: '2026-07-12T08:00:00.000Z',
    updatedAt: '2026-08-15T09:00:00.000Z',
    careNotes: [
      {
        id: 'care3',
        note: 'Đã gửi bảng giá khu Đông',
        employeeId: MOCK_STAFF.id,
        employeeName: MOCK_STAFF.fullName,
        createdAt: '2026-08-15T09:00:00.000Z',
      },
    ],
  }),
  staffCustomer({
    id: 'cus_pin_4',
    fullName: 'Phạm Thu Hà',
    status: CustomerStatus.KHACH_MOI,
    budgetMinVnd: 2_000_000_000,
    budgetMaxVnd: 3_000_000_000,
    note: null,
    isPinned: true,
    isHidden: false,
    primaryPhone: '0938111222',
    phones: [{ id: 'ph7', phone: '0938111222', label: null }],
    facebook: {
      customerUid: 'fb_page_ha',
      threadId: 'thread_ha',
      facebookName: 'Bùi Xuân Khả',
      avatarUrl: null,
      scanSource: 'page',
    },
    latestCareNote: null,
    lodatCount: 0,
    createdAt: '2026-08-01T08:00:00.000Z',
    updatedAt: '2026-08-14T11:00:00.000Z',
    careNotes: [],
  }),
  staffCustomer({
    id: 'cus_5',
    fullName: 'Đỗ Minh Tuấn',
    status: CustomerStatus.KHACH_CAN_CHAM_SOC,
    budgetMinVnd: null,
    budgetMaxVnd: null,
    note: 'Hỏi thổ cư Sóc Sơn',
    isPinned: false,
    isHidden: false,
    primaryPhone: '0965123456',
    phones: [{ id: 'ph8', phone: '0965123456', label: null }],
    facebook: null,
    latestCareNote: 'Gọi 2 lần chưa nghe máy',
    lodatCount: 0,
    createdAt: '2026-07-20T08:00:00.000Z',
    updatedAt: '2026-08-12T08:00:00.000Z',
    careNotes: [
      {
        id: 'care4',
        note: 'Gọi 2 lần chưa nghe máy',
        employeeId: MOCK_STAFF.id,
        employeeName: MOCK_STAFF.fullName,
        createdAt: '2026-08-12T08:00:00.000Z',
      },
    ],
  }),
  staffCustomer({
    id: 'cus_6',
    fullName: 'Ngô Thị Lan',
    status: CustomerStatus.KHACH_NET,
    budgetMinVnd: 1_000_000_000,
    budgetMaxVnd: 1_500_000_000,
    note: 'Muốn lô góc, ô tô vào',
    isPinned: false,
    isHidden: false,
    primaryPhone: '0988123456',
    phones: [{ id: 'ph9', phone: '0988123456', label: 'Zalo' }],
    facebook: {
      customerUid: 'fb_lan',
      threadId: 'thread_lan',
      facebookName: 'Ngo Thi Lan',
      avatarUrl: null,
      scanSource: 'messenger',
    },
    latestCareNote: 'Chốt xem đất thứ 7',
    lodatCount: 3,
    createdAt: '2026-05-10T08:00:00.000Z',
    updatedAt: '2026-08-11T16:00:00.000Z',
    careNotes: [
      {
        id: 'care5',
        note: 'Chốt xem đất thứ 7',
        employeeId: MOCK_STAFF.id,
        employeeName: MOCK_STAFF.fullName,
        createdAt: '2026-08-11T16:00:00.000Z',
      },
    ],
  }),
  staffCustomer({
    id: 'cus_7',
    fullName: 'Vũ Đức Thành',
    status: CustomerStatus.KHACH_MOI,
    budgetMinVnd: null,
    budgetMaxVnd: null,
    note: null,
    isPinned: false,
    isHidden: false,
    primaryPhone: null,
    phones: [],
    facebook: null,
    latestCareNote: null,
    lodatCount: 0,
    createdAt: '2026-08-08T08:00:00.000Z',
    updatedAt: '2026-08-10T08:00:00.000Z',
    careNotes: [],
  }),
  staffCustomer({
    id: 'cus_8',
    fullName: 'Hoàng Mai Anh',
    status: CustomerStatus.KHACH_NET,
    budgetMinVnd: 3_000_000_000,
    budgetMaxVnd: 4_000_000_000,
    note: 'Đầu tư 2 lô liền kề',
    isPinned: false,
    isHidden: false,
    primaryPhone: '0919000111',
    phones: [{ id: 'ph11', phone: '0919000111', label: null }],
    facebook: {
      customerUid: 'fb_mai',
      threadId: 'thread_mai',
      facebookName: 'Hoang Mai Anh',
      avatarUrl: null,
      scanSource: 'page',
    },
    latestCareNote: 'Đã gửi pháp lý dự án',
    lodatCount: 2,
    createdAt: '2026-04-01T08:00:00.000Z',
    updatedAt: '2026-08-09T12:00:00.000Z',
    careNotes: [
      {
        id: 'care6',
        note: 'Đã gửi pháp lý dự án',
        employeeId: MOCK_STAFF.id,
        employeeName: MOCK_STAFF.fullName,
        createdAt: '2026-08-09T12:00:00.000Z',
      },
    ],
  }),
  staffCustomer({
    id: 'cus_9',
    fullName: 'Bùi Quang Huy',
    status: CustomerStatus.KHACH_MOI,
    budgetMinVnd: 500_000_000,
    budgetMaxVnd: 800_000_000,
    note: 'Hỏi đất nền giá mềm',
    isPinned: false,
    isHidden: false,
    primaryPhone: '0902111222',
    phones: [{ id: 'ph12', phone: '0902111222', label: 'Zalo' }],
    facebook: null,
    latestCareNote: 'Gửi bảng giá khu Tây',
    lodatCount: 0,
    createdAt: '2026-08-02T08:00:00.000Z',
    updatedAt: '2026-08-08T10:00:00.000Z',
    careNotes: [
      {
        id: 'care7',
        note: 'Gửi bảng giá khu Tây',
        employeeId: MOCK_STAFF.id,
        employeeName: MOCK_STAFF.fullName,
        createdAt: '2026-08-08T10:00:00.000Z',
      },
    ],
  }),
  staffCustomer({
    id: 'cus_10',
    fullName: 'Trịnh Bảo Ngọc',
    status: CustomerStatus.KHACH_NET,
    budgetMinVnd: 1_800_000_000,
    budgetMaxVnd: 2_200_000_000,
    note: 'Cần lô gần trường học',
    isPinned: false,
    isHidden: false,
    primaryPhone: '0912333444',
    phones: [{ id: 'ph13', phone: '0912333444', label: null }],
    facebook: {
      customerUid: 'fb_ngoc',
      threadId: 'thread_ngoc',
      facebookName: 'Trinh Bao Ngoc',
      avatarUrl: null,
      scanSource: 'messenger',
    },
    latestCareNote: 'Hẹn xem đất thứ 6',
    lodatCount: 1,
    createdAt: '2026-06-20T08:00:00.000Z',
    updatedAt: '2026-08-07T14:00:00.000Z',
    careNotes: [
      {
        id: 'care8',
        note: 'Hẹn xem đất thứ 6',
        employeeId: MOCK_STAFF.id,
        employeeName: MOCK_STAFF.fullName,
        createdAt: '2026-08-07T14:00:00.000Z',
      },
    ],
  }),
  staffCustomer({
    id: 'cus_11',
    fullName: 'Phan Văn Khoa',
    status: CustomerStatus.KHACH_CAN_CHAM_SOC,
    budgetMinVnd: null,
    budgetMaxVnd: null,
    note: 'Hỏi thổ cư Biên Hòa',
    isPinned: false,
    isHidden: false,
    primaryPhone: '0988777666',
    phones: [{ id: 'ph14', phone: '0988777666', label: null }],
    facebook: null,
    latestCareNote: 'Chưa nghe máy lần 1',
    lodatCount: 0,
    createdAt: '2026-07-28T08:00:00.000Z',
    updatedAt: '2026-08-06T09:00:00.000Z',
    careNotes: [
      {
        id: 'care9',
        note: 'Chưa nghe máy lần 1',
        employeeId: MOCK_STAFF.id,
        employeeName: MOCK_STAFF.fullName,
        createdAt: '2026-08-06T09:00:00.000Z',
      },
    ],
  }),
  staffCustomer({
    id: 'cus_12',
    fullName: 'Đặng Thu Trang',
    status: CustomerStatus.KHACH_MOI,
    budgetMinVnd: 2_500_000_000,
    budgetMaxVnd: 3_500_000_000,
    note: 'Mua đầu tư cho thuê',
    isPinned: false,
    isHidden: false,
    primaryPhone: null,
    phones: [],
    facebook: {
      customerUid: 'fb_trang',
      threadId: 'thread_trang',
      facebookName: 'Dang Thu Trang',
      avatarUrl: null,
      scanSource: 'page',
    },
    latestCareNote: null,
    lodatCount: 0,
    createdAt: '2026-08-05T08:00:00.000Z',
    updatedAt: '2026-08-05T18:00:00.000Z',
    careNotes: [],
  }),
  staffCustomer({
    id: 'cus_13',
    fullName: 'Lý Minh Đức',
    status: CustomerStatus.KHACH_NET,
    budgetMinVnd: 900_000_000,
    budgetMaxVnd: 1_100_000_000,
    note: 'Lô góc đường 12m',
    isPinned: false,
    isHidden: false,
    primaryPhone: '0977000111',
    phones: [{ id: 'ph16', phone: '0977000111', label: null }],
    facebook: null,
    latestCareNote: 'Đã chốt giá chủ',
    lodatCount: 2,
    createdAt: '2026-05-15T08:00:00.000Z',
    updatedAt: '2026-08-04T11:00:00.000Z',
    careNotes: [
      {
        id: 'care10',
        note: 'Đã chốt giá chủ',
        employeeId: MOCK_STAFF.id,
        employeeName: MOCK_STAFF.fullName,
        createdAt: '2026-08-04T11:00:00.000Z',
      },
    ],
  }),
  staffCustomer({
    id: 'cus_14',
    fullName: 'Cao Thị Huyền',
    status: CustomerStatus.KHACH_MOI,
    budgetMinVnd: null,
    budgetMaxVnd: null,
    note: 'Hỏi sổ đỏ nhanh',
    isPinned: false,
    isHidden: false,
    primaryPhone: '0966123456',
    phones: [{ id: 'ph17', phone: '0966123456', label: null }],
    facebook: {
      customerUid: 'fb_huyen',
      threadId: 'thread_huyen',
      facebookName: 'Cao Thi Huyen',
      avatarUrl: null,
      scanSource: 'business_suite',
    },
    latestCareNote: 'Giới thiệu dịch vụ sổ đỏ',
    lodatCount: 0,
    createdAt: '2026-08-03T08:00:00.000Z',
    updatedAt: '2026-08-03T16:00:00.000Z',
    careNotes: [
      {
        id: 'care11',
        note: 'Giới thiệu dịch vụ sổ đỏ',
        employeeId: MOCK_STAFF.id,
        employeeName: MOCK_STAFF.fullName,
        createdAt: '2026-08-03T16:00:00.000Z',
      },
    ],
  }),
  staffCustomer({
    id: 'cus_15',
    fullName: 'Nguyễn Thanh Sơn',
    status: CustomerStatus.KHACH_CAN_CHAM_SOC,
    budgetMinVnd: 1_200_000_000,
    budgetMaxVnd: 1_600_000_000,
    note: 'Đất vườn Long Thành',
    isPinned: false,
    isHidden: false,
    primaryPhone: '0944888999',
    phones: [{ id: 'ph18', phone: '0944888999', label: 'Chính' }],
    facebook: null,
    latestCareNote: 'Gọi lại tuần sau',
    lodatCount: 1,
    createdAt: '2026-06-01T08:00:00.000Z',
    updatedAt: '2026-08-02T08:00:00.000Z',
    careNotes: [
      {
        id: 'care12',
        note: 'Gọi lại tuần sau',
        employeeId: MOCK_STAFF.id,
        employeeName: MOCK_STAFF.fullName,
        createdAt: '2026-08-02T08:00:00.000Z',
      },
    ],
  }),
  staffCustomer({
    id: 'cus_16',
    fullName: 'Trần Kim Oanh',
    status: CustomerStatus.KHACH_NET,
    budgetMinVnd: 4_000_000_000,
    budgetMaxVnd: 5_000_000_000,
    note: 'Nhà phố 2 mặt tiền',
    isPinned: false,
    isHidden: false,
    primaryPhone: '0909999888',
    phones: [{ id: 'ph19', phone: '0909999888', label: null }],
    facebook: {
      customerUid: 'fb_oanh',
      threadId: 'thread_oanh',
      facebookName: 'Tran Kim Oanh',
      avatarUrl: null,
      scanSource: 'page',
    },
    latestCareNote: 'Gửi pháp lý + ảnh thực tế',
    lodatCount: 1,
    createdAt: '2026-03-12T08:00:00.000Z',
    updatedAt: '2026-08-01T15:00:00.000Z',
    careNotes: [
      {
        id: 'care13',
        note: 'Gửi pháp lý + ảnh thực tế',
        employeeId: MOCK_STAFF.id,
        employeeName: MOCK_STAFF.fullName,
        createdAt: '2026-08-01T15:00:00.000Z',
      },
    ],
  }),
  staffCustomer({
    id: 'cus_17',
    fullName: 'Hồ Văn Phong',
    status: CustomerStatus.KHACH_MOI,
    budgetMinVnd: 700_000_000,
    budgetMaxVnd: 950_000_000,
    note: null,
    isPinned: false,
    isHidden: false,
    primaryPhone: '0922111000',
    phones: [{ id: 'ph20', phone: '0922111000', label: null }],
    facebook: null,
    latestCareNote: null,
    lodatCount: 0,
    createdAt: '2026-07-30T08:00:00.000Z',
    updatedAt: '2026-07-31T08:00:00.000Z',
    careNotes: [],
  }),
  staffCustomer({
    id: 'cus_18',
    fullName: 'Mai Phương Thảo',
    status: CustomerStatus.KHACH_NET,
    budgetMinVnd: 1_400_000_000,
    budgetMaxVnd: 1_700_000_000,
    note: 'Lô gần công viên',
    isPinned: false,
    isHidden: false,
    primaryPhone: '0933666555',
    phones: [{ id: 'ph21', phone: '0933666555', label: 'Zalo' }],
    facebook: {
      customerUid: 'fb_thao',
      threadId: 'thread_thao',
      facebookName: 'Mai Phuong Thao',
      avatarUrl: null,
      scanSource: 'messenger',
    },
    latestCareNote: 'Đang so sánh 2 lô',
    lodatCount: 2,
    createdAt: '2026-04-22T08:00:00.000Z',
    updatedAt: '2026-07-29T12:00:00.000Z',
    careNotes: [
      {
        id: 'care14',
        note: 'Đang so sánh 2 lô',
        employeeId: MOCK_STAFF.id,
        employeeName: MOCK_STAFF.fullName,
        createdAt: '2026-07-29T12:00:00.000Z',
      },
    ],
  }),
  {
    id: 'cus_hidden',
    employeeId: MOCK_STAFF.id,
    employeeName: MOCK_STAFF.fullName,
    fullName: 'Lê Văn C (đã ẩn)',
    status: CustomerStatus.KHACH_CAN_CHAM_SOC,
    budgetMinVnd: null,
    budgetMaxVnd: null,
    note: 'Spam / không liên hệ được',
    isPinned: false,
    isHidden: true,
    primaryPhone: '0923456789',
    phones: [{ id: 'ph4', phone: '0923456789', label: null }],
    facebook: null,
    latestCareNote: null,
    lodatCount: 0,
    createdAt: '2026-05-01T08:00:00.000Z',
    updatedAt: '2026-07-20T12:00:00.000Z',
    careNotes: [],
  },
  {
    id: 'cus_other_staff',
    employeeId: OTHER_EMPLOYEE_ID,
    employeeName: 'Khả Khánh Hà',
    fullName: 'Phạm Thị Dung',
    status: CustomerStatus.KHACH_MOI,
    budgetMinVnd: null,
    budgetMaxVnd: null,
    note: null,
    isPinned: false,
    isHidden: false,
    primaryPhone: '0934567890',
    phones: [{ id: 'ph5', phone: '0934567890', label: null }],
    facebook: {
      customerUid: 'fb_other',
      facebookName: 'Pham Thi Dung',
      threadId: 'thread_other',
      avatarUrl: null,
      scanSource: 'messenger',
    },
    latestCareNote: null,
    lodatCount: 1,
    createdAt: '2026-07-10T08:00:00.000Z',
    updatedAt: '2026-08-05T08:00:00.000Z',
    careNotes: [],
  },
];

export const mockChats: Record<string, CustomerMessengerMessage[]> = {
  cus_moi_fb: [
    {
      id: 'm1',
      sender: 'customer',
      body: 'Anh ơi lô mặt tiền còn không?',
      sortOrder: 0,
      images: [],
    },
    {
      id: 'm2',
      sender: 'me',
      body: 'Em gửi ảnh và giá ạ, anh xem giúp.',
      sortOrder: 1,
      images: [],
    },
  ],
  cus_net_phones: [
    {
      id: 'm3',
      sender: 'me',
      body: 'Chị Bích ơi, chủ nhật mình xem lô 38 nhé.',
      sortOrder: 0,
      images: [],
    },
    {
      id: 'm4',
      sender: 'customer',
      body: 'Ok anh, 9h em ra.',
      sortOrder: 1,
      images: [],
    },
  ],
  cus_6: [
    {
      id: 'm5',
      sender: 'customer',
      body: 'Lô góc còn không anh?',
      sortOrder: 0,
      images: [],
    },
  ],
};

export type MockLodatBrief = {
  id: string;
  title: string;
  area: string;
  price: string;
};

export const mockLodatsByCustomer: Record<string, MockLodatBrief[]> = {
  cus_net_phones: [
    { id: 'ld1', title: 'Lô 38 Quán Táo Đông', area: '80 m²', price: '1,85 tỷ' },
    { id: 'ld2', title: 'Lô 12 đường 21m', area: '90 m²', price: '2,1 tỷ' },
  ],
  cus_pin_3: [{ id: 'ld3', title: 'Lô gần ĐT 296', area: '72 m²', price: '980 triệu' }],
  cus_6: [
    { id: 'ld4', title: 'Lô góc ô tô vào', area: '100 m²', price: '1,35 tỷ' },
    { id: 'ld5', title: 'Lô 5 thổ cư', area: '88 m²', price: '1,2 tỷ' },
    { id: 'ld6', title: 'Lô 9 dự án', area: '75 m²', price: '1,15 tỷ' },
  ],
  cus_8: [
    { id: 'ld7', title: 'Liền kề A1', area: '120 m²', price: '3,2 tỷ' },
    { id: 'ld8', title: 'Liền kề A2', area: '120 m²', price: '3,2 tỷ' },
  ],
};
