import {
  CustomerStatus,
  UserRole,
  type AuthUser,
  type CustomerDetail,
} from '@crmanhung/shared';

export const MOCK_STAFF: AuthUser = {
  id: 'user_staff_1',
  username: 'staff',
  fullName: 'Nhân viên Demo',
  role: UserRole.STAFF,
};

export const MOCK_ADMIN: AuthUser = {
  id: 'user_admin_1',
  username: 'admin',
  fullName: 'Admin Demo',
  role: UserRole.ADMIN,
};

/** Khách nhân viên khác — STAFF không thấy trong list (trừ ADMIN). */
const OTHER_EMPLOYEE_ID = 'user_staff_other';

/** Mock kênh liên hệ — UI staff (chưa có field trên contract P1). */
export const MOCK_CONTACT_CHANNELS: Record<string, string> = {
  cus_moi_fb: 'Page Demo An Hưng',
  cus_net_phones: '0977656280 (Zalo Demo)',
  cus_hidden: '0977656280 (Zalo Demo)',
  cus_other_staff: 'Page Nhân viên Khác',
  cus_khac: 'Page Demo An Hưng',
  cus_net_2: 'Khả Khánh Hà',
  cus_moi_2: '0977656280 (Zalo Demo)',
  cus_moi_3: 'Page Demo An Hưng',
  cus_care_1: '0929280288 (Zalo Em Hà)',
};

export const MOCK_CONTACT_CHANNEL_OPTIONS = [
  'Page Demo An Hưng',
  '0977656280 (Zalo Demo)',
  'Khả Khánh Hà',
  '0929280288 (Zalo Em Hà)',
] as const;

export const mockCustomers: CustomerDetail[] = [
  {
    id: 'cus_net_2',
    employeeId: MOCK_STAFF.id,
    employeeName: MOCK_STAFF.fullName,
    fullName: 'Huyền Trần',
    status: CustomerStatus.KHACH_NET,
    budgetMinVnd: 1_500_000_000,
    budgetMaxVnd: 2_000_000_000,
    note: 'Hỏi lô 38 Quán táo đông',
    isPinned: true,
    isHidden: false,
    primaryPhone: '0901111222',
    phones: [{ id: 'ph_n2', phone: '0901111222', label: null }],
    facebook: {
      customerUid: 'fb_huyen',
      threadId: 'thread_huyen',
      facebookName: 'Huyen Tran',
      avatarUrl: null,
      scanSource: 'business_suite',
    },
    latestCareNote: 'Đã gọi xác nhận nhu cầu',
    lodatCount: 1,
    createdAt: '2026-07-01T08:00:00.000Z',
    updatedAt: '2026-08-15T10:00:00.000Z',
    careNotes: [
      {
        id: 'care_n2',
        note: 'Đã gọi xác nhận nhu cầu',
        employeeId: MOCK_STAFF.id,
        employeeName: MOCK_STAFF.fullName,
        createdAt: '2026-08-15T10:00:00.000Z',
      },
    ],
  },
  {
    id: 'cus_moi_2',
    employeeId: MOCK_STAFF.id,
    employeeName: MOCK_STAFF.fullName,
    fullName: 'Minh Quý',
    status: CustomerStatus.KHACH_NET,
    budgetMinVnd: 2_000_000_000,
    budgetMaxVnd: 2_500_000_000,
    note: 'Cần mua Đồng Khê',
    isPinned: true,
    isHidden: false,
    primaryPhone: '0902222333',
    phones: [{ id: 'ph_mq', phone: '0902222333', label: 'Zalo' }],
    facebook: null,
    latestCareNote: 'Hẹn xem đất cuối tuần',
    lodatCount: 0,
    createdAt: '2026-07-05T08:00:00.000Z',
    updatedAt: '2026-08-14T10:00:00.000Z',
    careNotes: [
      {
        id: 'care_mq',
        note: 'Hẹn xem đất cuối tuần',
        employeeId: MOCK_STAFF.id,
        employeeName: MOCK_STAFF.fullName,
        createdAt: '2026-08-14T10:00:00.000Z',
      },
    ],
  },
  {
    id: 'cus_moi_fb',
    employeeId: MOCK_STAFF.id,
    employeeName: MOCK_STAFF.fullName,
    fullName: 'Nguyễn Văn A',
    status: CustomerStatus.KHACH_MOI,
    budgetMinVnd: 2_000_000_000,
    budgetMaxVnd: 2_500_000_000,
    note: 'Hỏi lô 80m2 mặt tiền 4m trục chính An Lâm',
    isPinned: true,
    isHidden: false,
    primaryPhone: '0901234567',
    phones: [{ id: 'ph1', phone: '0901234567', label: 'Zalo' }],
    facebook: {
      customerUid: 'fb_1001',
      threadId: 'thread_1001',
      facebookName: 'Nguyen Van A FB',
      avatarUrl: null,
      scanSource: 'business_suite',
    },
    latestCareNote: 'Vừa inbox hỏi lô mặt tiền',
    lodatCount: 0,
    createdAt: '2026-07-01T08:00:00.000Z',
    updatedAt: '2026-08-09T10:00:00.000Z',
    careNotes: [
      {
        id: 'care1',
        note: 'Vừa inbox hỏi lô mặt tiền',
        employeeId: MOCK_STAFF.id,
        employeeName: MOCK_STAFF.fullName,
        createdAt: '2026-08-09T10:00:00.000Z',
      },
    ],
  },
  {
    id: 'cus_care_1',
    employeeId: MOCK_STAFF.id,
    employeeName: MOCK_STAFF.fullName,
    fullName: 'Anh Mười',
    status: CustomerStatus.KHACH_MOI,
    budgetMinVnd: null,
    budgetMaxVnd: null,
    note: 'Đang cần bán lô lk4.2 Đồn Khê. giá có thể thương lượng.',
    isPinned: true,
    isHidden: false,
    primaryPhone: '0918888999',
    phones: [{ id: 'ph_m', phone: '0918888999', label: null }],
    facebook: null,
    latestCareNote: null,
    lodatCount: 1,
    createdAt: '2026-07-12T08:00:00.000Z',
    updatedAt: '2026-08-12T10:00:00.000Z',
    careNotes: [],
  },
  {
    id: 'cus_net_phones',
    employeeId: MOCK_STAFF.id,
    employeeName: MOCK_STAFF.fullName,
    fullName: 'Trần Thị B',
    status: CustomerStatus.KHACH_NET,
    budgetMinVnd: 1_000_000_000,
    budgetMaxVnd: 2_000_000_000,
    note: 'Quan tâm khu Đông',
    isPinned: false,
    isHidden: false,
    primaryPhone: '0912345678',
    phones: [
      { id: 'ph2', phone: '0912345678', label: 'Chính' },
      { id: 'ph3', phone: '0987654321', label: 'Phụ' },
    ],
    facebook: null,
    latestCareNote: 'Hẹn xem đất cuối tuần',
    lodatCount: 2,
    createdAt: '2026-06-15T08:00:00.000Z',
    updatedAt: '2026-08-08T15:30:00.000Z',
    careNotes: [
      {
        id: 'care2',
        note: 'Hẹn xem đất cuối tuần',
        employeeId: MOCK_STAFF.id,
        employeeName: MOCK_STAFF.fullName,
        createdAt: '2026-08-08T15:30:00.000Z',
      },
      {
        id: 'care3',
        note: 'Đã gửi bảng giá 3 lô',
        employeeId: MOCK_STAFF.id,
        employeeName: MOCK_STAFF.fullName,
        createdAt: '2026-08-01T09:00:00.000Z',
      },
    ],
  },
  {
    id: 'cus_moi_3',
    employeeId: MOCK_STAFF.id,
    employeeName: MOCK_STAFF.fullName,
    fullName: 'Nguyễn Nhung',
    status: CustomerStatus.KHACH_MOI,
    budgetMinVnd: null,
    budgetMaxVnd: null,
    note: null,
    isPinned: false,
    isHidden: false,
    primaryPhone: null,
    phones: [],
    facebook: {
      customerUid: 'fb_nhung',
      threadId: 'thread_nhung',
      facebookName: 'Nguyen Nhung',
      avatarUrl: null,
      scanSource: 'messenger',
    },
    latestCareNote: null,
    lodatCount: 0,
    createdAt: '2026-08-01T08:00:00.000Z',
    updatedAt: '2026-08-11T08:00:00.000Z',
    careNotes: [],
  },
  {
    id: 'cus_khac',
    employeeId: MOCK_STAFF.id,
    employeeName: MOCK_STAFF.fullName,
    fullName: 'Hoàng Minh E',
    status: CustomerStatus.KHAC,
    budgetMinVnd: 500_000_000,
    budgetMaxVnd: 800_000_000,
    note: 'Chưa rõ nhu cầu',
    isPinned: false,
    isHidden: false,
    primaryPhone: '0945678901',
    phones: [{ id: 'ph6', phone: '0945678901', label: null }],
    facebook: {
      customerUid: 'fb_e',
      threadId: 'thread_e',
      facebookName: 'Hoang Minh E',
      avatarUrl: null,
      scanSource: 'messenger',
    },
    latestCareNote: 'Nhắn lại tuần sau',
    lodatCount: 0,
    createdAt: '2026-07-20T08:00:00.000Z',
    updatedAt: '2026-08-10T08:00:00.000Z',
    careNotes: [
      {
        id: 'care4',
        note: 'Nhắn lại tuần sau',
        employeeId: MOCK_STAFF.id,
        employeeName: MOCK_STAFF.fullName,
        createdAt: '2026-08-10T08:00:00.000Z',
      },
    ],
  },
  {
    id: 'cus_hidden',
    employeeId: MOCK_STAFF.id,
    employeeName: MOCK_STAFF.fullName,
    fullName: 'Lê Văn C (đã ẩn)',
    status: CustomerStatus.KHACH_CAN_CHAM_SOC,
    budgetMinVnd: null,
    budgetMaxVnd: null,
    note: 'Spam / không liên hệ được',
    isPinned: false,
    isHidden: true,
    primaryPhone: '0923456789',
    phones: [{ id: 'ph4', phone: '0923456789', label: null }],
    facebook: null,
    latestCareNote: null,
    lodatCount: 0,
    createdAt: '2026-05-01T08:00:00.000Z',
    updatedAt: '2026-07-20T12:00:00.000Z',
    careNotes: [],
  },
  {
    id: 'cus_other_staff',
    employeeId: OTHER_EMPLOYEE_ID,
    employeeName: 'Nhân viên Khác',
    fullName: 'Phạm Thị D',
    status: CustomerStatus.KHACH_MOI,
    budgetMinVnd: null,
    budgetMaxVnd: null,
    note: null,
    isPinned: false,
    isHidden: false,
    primaryPhone: '0934567890',
    phones: [{ id: 'ph5', phone: '0934567890', label: null }],
    facebook: {
      customerUid: 'fb_other',
      facebookName: 'Pham Thi D',
      threadId: 'thread_other',
      avatarUrl: null,
      scanSource: 'messenger',
    },
    latestCareNote: null,
    lodatCount: 1,
    createdAt: '2026-07-10T08:00:00.000Z',
    updatedAt: '2026-08-05T08:00:00.000Z',
    careNotes: [],
  },
];

export function contactChannelOf(id: string) {
  return MOCK_CONTACT_CHANNELS[id] ?? '—';
}
